### PR TITLE
Ported to 1.20

### PR DESCRIPTION
**Pull request by jquann1998**
Sorry to burst your bubble but, I didn't give up on porting this mod to 1.20! I did follow the steps just like you said back in my first account "gohkenytp" and it was successful. So by any means, can you accept my PR?

### CODE REVIEW

**Comment by bl4ckscor3** [comment]
I told you that I do not want to interact with you anymore. You ignoring my wish and evading it, paired with the submission of yet another PR that does not address my remaining comments from the other one doesn't make me want to rethink my decision. Please stop.

**Comment by jquann1998** [comment]
Well sorry, I didn't mean to startle you. I didn't mean to cause any trouble! I'm not here for crazy shenangians. I'm here to tell you that I didn't give up on porting this mod to 1.20!

**Comment by jquann1998** [comment]
I'll try to promise you that I can port your mods to 1.20! Please understand?

**Comment by jquann1998** [comment]
I'm really sorry for being a jerk to you.

**Pull request closed without merging**
